# Generated by Django 5.0.4 on 2024-06-06 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nfc_id', models.CharField(default='', max_length=100)),
                ('horas_acordadas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lider_de', to='members.miembro')),
            ],
        ),
        migrations.AddField(
            model_name='miembro',
            name='mision',
            field=models.ManyToManyField(to='members.mision'),
        ),
        migrations.CreateModel(
            name='Subsistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lider', to='members.miembro')),
            ],
        ),
        migrations.AddField(
            model_name='miembro',
            name='subsistema',
            field=models.ManyToManyField(to='members.subsistema'),
        ),
    ]
