# Generated by Django 5.0.4 on 2024-06-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_miembro_email_miembro_groups_miembro_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
