# Generated by Django 5.0.4 on 2024-06-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_miembro_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='nfc_id',
        ),
        migrations.AddField(
            model_name='miembro',
            name='role',
            field=models.CharField(choices=[('M', 'MEMBER'), ('L', 'LEADER'), ('A', 'ADMIN')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='horas_acordadas',
            field=models.IntegerField(default=0),
        ),
    ]
