# Generated by Django 5.0.4 on 2024-06-07 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_miembro_nfc_id_miembro_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='is_admin',
        ),
    ]
