# Generated by Django 5.0.4 on 2024-06-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_miembro_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='photo',
            field=models.ImageField(default='', upload_to='users_photo_profile'),
        ),
    ]
