# Generated by Django 5.0.4 on 2024-06-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_miembro_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='photo',
        ),
        migrations.AddField(
            model_name='miembro',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='users_profile_picture'),
        ),
    ]
