# Generated by Django 5.0.4 on 2024-06-16 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_remove_miembro_photo_miembro_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miembro',
            old_name='nombre',
            new_name='first_names',
        ),
        migrations.RenameField(
            model_name='miembro',
            old_name='horas_acordadas',
            new_name='hours_per_week',
        ),
        migrations.AddField(
            model_name='miembro',
            name='last_names',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miembro',
            name='schedule',
            field=models.ImageField(blank=True, upload_to='schedules'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='profile_picture',
            field=models.ImageField(default='default_profile_picture.jpg', upload_to='users_profile_picture'),
        ),
    ]
