# Generated by Django 5.0.4 on 2024-06-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_rename_nombre_miembro_first_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='first_names',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='last_names',
            field=models.CharField(default='', max_length=100),
        ),
    ]
