# Generated by Django 5.0.4 on 2024-06-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_miembro_first_names_alter_miembro_last_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='miembro',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='miembro',
            name='user_permissions',
        ),
    ]
