# Generated by Django 5.0.4 on 2024-06-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_miembro_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='profile_picture',
            field=models.ImageField(default='users_profile_picture/default_profile_picture.jpg', upload_to='users_profile_picture'),
        ),
    ]
