# Generated by Django 5.0.4 on 2024-06-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_alter_miembro_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='profile_picture',
            field=models.ImageField(default='users_profile_picture/default_profile_picture.jpg', upload_to='users_profile_picture/yeap.jpg'),
        ),
    ]
