# Generated by Django 5.0.4 on 2024-07-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0001_initial'),
        ('members', '0015_alter_miembro_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsistema',
            name='lider',
        ),
        migrations.AlterField(
            model_name='miembro',
            name='mision',
            field=models.ManyToManyField(to='divisions.mision'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='subsistema',
            field=models.ManyToManyField(to='divisions.subsistema'),
        ),
        migrations.DeleteModel(
            name='Mision',
        ),
        migrations.DeleteModel(
            name='Subsistema',
        ),
    ]
