# Generated by Django 5.0.4 on 2024-04-27 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mision',
            name='lider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lider_de', to='registro.miembro'),
        ),
    ]
