# Generated by Django 5.0.4 on 2024-04-27 21:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_mision_lider'),
    ]

    operations = [
        migrations.AddField(
            model_name='mision',
            name='fecha_finalizacion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mision',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mision',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lider_de', to='registro.miembro'),
        ),
    ]
