# Generated by Django 5.0.4 on 2024-04-29 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_mision_fecha_finalizacion_mision_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mision',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lider_de', to='registro.miembro'),
        ),
    ]
