# Generated by Django 5.0.4 on 2024-04-29 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_alter_mision_lider'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsistema',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lider', to='registro.miembro'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembro_de', to='registro.miembro'),
        ),
    ]
