# Generated by Django 5.0.4 on 2024-04-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_subsistema_lider_alter_registro_miembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='horas_acordadas',
            field=models.IntegerField(default=0),
        ),
    ]
