# Generated by Django 5.0.4 on 2024-07-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0014_alter_register_check_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='check_in_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='check_out_time',
            field=models.TimeField(null=True),
        ),
    ]
